---
  slug: application-phase
  name: Aplications will be open soon!
  date: "2020-08-15T20:00:00+02:00"
  description: |
    We will be posting the application form here, stay tuned!

  #  Our topics include:

  #  1. **Key Facts** regarding TechLabs, the Digital Shaper program, certificate and community
  #  1. **Administrative Topics** – your onboarding to our toolset, communication channels, regular meetings & next steps
  #  1. **Community Get-Together** – we want to get to know each other
  #  1. **Track Get-Together** – you'll meet other participants in the track you're planning to choose
  forms: []
  # - title: Feedback
  #   description: Please leave feedback for our Kick-Off Event!
  #   url: https://techlabsorg.typeform.com/to/SCoGA7
  resources: []
    # - title: "Meet: Kick-Off"
    #   description: The main room where we will meet.
    #   type: meeting
    #   url: https://meet.google.com/hts-nbqy-kop
    # - title: "Meet: DS"
    #   description: Break-Out Room for Data Science
    #   type: meeting
    #   url: https://meet.google.com/ept-mmdn-nyx
    # - title: "Meet: AI"
    #   description: Break-Out Room for Artificial Intelligence
    #   type: meeting
    #   url: https://meet.google.com/vam-djgi-iof
    # - title: "Meet: WebDev"
    #   description: Break-Out Room for Web Development
    #   type: meeting
    #   url: https://meet.google.com/prb-ifih-qnt
    # - title: "Meet: UX"
    #   description: Break-Out Room for UX Design
    #   type: meeting
    #   url: https://meet.google.com/aep-cocb-wyq
    #- title: "FAQ"
    # description: Frequently asked questions and answers
    #  type: link
    # url: https://codeathome.techlabs.org/faq
